# Generated by Django 5.0.1 on 2024-11-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_collection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.AddField(
            model_name='collection',
            name='user_username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
